on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t testoracle .

    - name: Test application
      run: |
        docker run --name test-container -d -p 8080:80 testoracle
        sleep 5
        curl http://localhost:8080 | grep "Hello, World!"
        docker stop test-container

    - name: Deploy to Oracle Cloud
      env:
        PRIVATE_KEY: ${{ secrets.ORACLE_PRIVATE_KEY }}
        HOST: ${{ secrets.ORACLE_HOST }}
        USER: ${{ secrets.ORACLE_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
          # Installer docker si on l'a pas 
          if ! command -v docker &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $USER

            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker -v
          fi
        EOF
    
    - name: Deploy to Oracle Cloud
      env:
        PRIVATE_KEY: ${{ secrets.ORACLE_PRIVATE_KEY }}
        HOST: ${{ secrets.ORACLE_HOST }}
        USER: ${{ secrets.ORACLE_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
          sudo docker pull myapp
          sudo docker stop myapp || true
          sudo docker rm myapp || true
          sudo docker run -d --name myapp -p 80:80 myapp
        EOF